version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studentscores"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10y2h1j8soecg"
s3_prefix = "studentscores"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
